### PR TITLE
Integration info

### PR DESCRIPTION
**Pull request by traumverloren**
updated the whole payment integration section with new examples, trying to clarify the steps better.

fixed more inaccurate links, add more terms to glossary, other minor editing fixes.

### CODE REVIEW

**Comment by tilsammans** [comment]
Good stuff, including the new spelling of sign2pay. 

Now that I see it, there is trouble. Nick has been writing these docs using haml source. He then generated the html from that and committed. Ugh. 

We have to either kill the haml or you'll have to redo your work and regenerate. What do you think?

**Comment by traumverloren** [comment]
@tilsammans where is the haml source?  

if that's what you guys want to stick with for future updates, it sounds like i need to redo and regenerate to stay in line.

**Comment by traumverloren** [comment]
@tilsammans ...and probably need to update the readme to clarify this point.

**Comment by nicklloyd** [comment]
Sorry folks, but yes this is written using html source. This is contained in the _remix_ branch. 

Hosting w gh-pages is becoming more and more of a pita. There is just way too much content + structure to do it all in markdown. Not to mention what will happen when this needs localisation... 

whats the markdown for :-(

**Comment by tilsammans** [comment]
Okay but for now we're stuck with this, it's a little cumbersome but it works.

I'll leave this PR open for @traumverloren to do the following:

- [ ] get the HAML source from the remix branch into gh-pages so we can work with it
- [ ] update the HAML based on the changes she made in the HTML (sorrrrryyy!!!)
- [ ] re-generate the HTML from the HAML and commit that too
- [ ] document this lovely procedure in the README
- [ ] drop the remix branch

**Pull request closed without merging**
